Repository Lux-AI-Challenge/Lux-Design-2021, pull requests merged in 2021-07, with the labels that each got.

#29 bugfix: cart has worker upkeep
  src/Unit/index.ts
Labels: bug, requires-visualizer-update

#42 change city to CityTile
  src/Game/index.ts
Labels: bug, enhancement

#36 Update and refactor isNight()
  src/Game/index.ts
  src/logic.ts
Labels: bug, requires-visualizer-update

#31 Fix incorrectly named variables in comment
  kits/js/simple/main.js
Labels: enhancement

#45 change dist calculation from L2 to L1
  kits/README.md
  kits/cpp/simple/lux/position.hpp
  kits/java/simple/lux/Position.java
  kits/js/simple/lux/map.js
  kits/python/simple/lux/game_map.py
Labels: enhancement

#38 Move cooldown into Actionable
  kits/cpp/simple/lux/game_objects.hpp
  kits/java/simple/lux/Unit.java
  kits/js/simple/lux/game_objects.js
  kits/python/simple/lux/game_objects.py
  src/Actionable/index.ts
  src/Game/city.ts
  src/Game/index.ts
  src/Unit/index.ts
Labels: enhancement

#39 refactor transferAmount
  ChangeLog.md
  README.md
  src/Game/index.ts
Labels: enhancement

#40 refactor agentsTerminated
  src/logic.ts
Labels: enhancement

#66 Actually fix Issue #56 and add include guards
  kits/cpp/simple.zip
  kits/cpp/simple/compile.bat
  kits/cpp/simple/compile.sh
  kits/cpp/simple/lux/annotate.hpp
  kits/cpp/simple/lux/constants.hpp
  kits/cpp/simple/lux/define.cpp
  kits/cpp/simple/lux/lux_io.hpp
  kits/cpp/simple/lux/position.hpp
  kits/cpp/simple/main.cpp
Labels: starter-kit

#62 Adding TypeScript kit
  kits/ts/README.md
  kits/ts/simple.zip
  kits/ts/simple/lux/Agent.ts
  kits/ts/simple/lux/Cell.ts
  kits/ts/simple/lux/City.ts
  kits/ts/simple/lux/CityTile.ts
  kits/ts/simple/lux/GameMap.ts
  kits/ts/simple/lux/Parsed.ts
  kits/ts/simple/lux/Parser.ts
  kits/ts/simple/lux/Player.ts
  kits/ts/simple/lux/Position.ts
  kits/ts/simple/lux/Unit.ts
  kits/ts/simple/lux/game_constants.json
  kits/ts/simple/lux/io.ts
  kits/ts/simple/main.py
  kits/ts/simple/main.ts
  kits/ts/simple/tsconfig.json
Labels: starter-kit
